
from classes.getData import GetData
from classes.addEmbeddings import Embeddings
import faiss
from pandas import DataFrame


DIMENSIONS = 3072 # this is the embedding vector size generated by llama3.2, phi3.5


def main():
    #get data and
    data = GetData.Links()
    #get embeddings fro dataset
    embed = Embeddings(data=data).Get()
    #vector db that will hold the index and the embeddings generated based on the text of each tuple
    index = faiss.IndexFlatL2(DIMENSIONS)#uses euclidean distance for all vector coordinates
    #normalize vectors
    faiss.normalize_L2(embed)
    #add the normalized embeddings to the vectorDB
    index.add(embed)
    #get user prompt, 
    prompt = "water related soil erosion"
    df = DataFrame(data = [prompt], columns = ['prompt'])
    userEmbed = Embeddings(data=df).Get()
    faiss.normalize_L2(userEmbed)
    #search index
    distances, indices = index.search(userEmbed, k=5)

    for i, index in enumerate(indices[0]):
        distance = distances[0][i]
        print(f"Nearest neighbor {i+1}: {data['link'][index]}, distance {distance}")

















if __name__ == "__main__":
    main()

